#!/usr/bin/env bash
# Generates Version.swift in each example app from package.json version.
# Called by the pre-commit hook automatically.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
VERSION=$(node -p "require('$ROOT_DIR/package.json').version")

TARGETS=(
  "examples/swift-media/SwiftMedia"
  "examples/swift-events/SwiftEvents"
  "examples/swift-users/SwiftUsers"
)

for TARGET in "${TARGETS[@]}"; do
  DIR="$ROOT_DIR/$TARGET"
  if [ -d "$DIR" ]; then
    cat > "$DIR/Version.swift" << EOF
// Auto-generated by scripts/generate-version.sh — do not edit manually
let toolkitVersion = "$VERSION"
EOF
  fi
done
