name: SwiftLint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - production

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: macos-15
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run SwiftLint
        uses: realm/SwiftLint@v0.58.2
        with:
          args: --reporter github-actions-logging Sources/
